#!/bin/bash -

#
# This script is a part of "set_environment" installer and should not be called directry.
# It got sourced from src/architecture/linux/continue_install.sh
#

# Table of contents generated by function file_toc():
#
#    - add_to_install_if_missing
#    - apt_install_basic_packages
#    - assert_baseline_components
#    - assert_core_credentials
#    - ff_agent_install
#    - ff_agent_install_bashrc
#    - ff_agent_logs_flush_install
#    - ff_agent_logs_show_install
#    - ff_agent_register_pm2_systemd
#    - ff_agent_restart_install
#    - ff_agent_run_pm2
#    - ff_agent_scripts_install
#    - ff_agent_update_install
#    - install_authbind
#    - install_go
#    - install_n
#    - install_nodejs
#    - install_nodejs_suite
#    - install_set_environment_baseline
#    - pm2_configure
#    - pm2_ensure
#    - pm2_install
#    - pm2_is_installed
#    - pm2_is_running_as_me
#    - pm2_start
#    - pm2_stop
#    - pm2_uninstall
#    - set_environment_ensure_ff_agent_bin_exists
#    - set_environment_ensure_install_exists
#    - set_environment_preserve_source_code
#    - set_script_logging
#    - setup_logging

################################################################################
#
# Return information if package is installed in system, dpkg depend
# @param ${1} string package name
# @param ${2} array package list to append
#
# Return code value:
#  0 - Success
#      Note: disregard of package is already installed or not, the success
#            for function "add_to_install_if_missing" means we checked and added
#            (if it was missing) and didn't face any errors.
#
#  1 - on error (e.g.: bad arguments)
#
# Usage: add_to_install_if_missing "vim" PACKAGES
#
function add_to_install_if_missing {

  # Check dependencies
  local DEPENDENCIES=(
    "error"
    "dpkg"
    "grep"
    "in_array"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || return 1  # Note: check_dependencies will report missing dependencies

  # Take argument ${1} - package name
  local PACKAGE="${1}"

  # Check inputs: ${PACKAGE} - must be not empty string (package name to check)
  if [ "${PACKAGE}" == "" ]; then
    error "${FUNCNAME[0]} bad arguments: package name is not specified (no arguments)"
    return 1
  fi

  # Take argument ${2} - reference to array
  declare -n PACKAGES_TO_INSTALL=${2}

  # Check inputs: ${PACKAGES_TO_INSTALL} - must be a reference to an array
  if [ "${PACKAGES_TO_INSTALL@a}" != "a" ]; then
    # Error: passed reference does not point to array
    error "${FUNCNAME[0]} bad arguments: 2nd argument must be reference to array"
    return 1
  fi

  # Check if given PACKAGE is already present in PACKAGES_TO_INSTALL array
  if in_array "${PACKAGE}" "${PACKAGES_TO_INSTALL[@]}"; then
    # Yes, already present, nothing to do
    return 0
  fi

	# Check if given package is already installed.
  # Note: grep exit code 0=installed, 1=not installed.
	# Note we use grep to cover case "Status: deinstall ok config-files" when package was uninstalled.
	dpkg --status ${PACKAGE} 2>/dev/null | grep --silent "installed"
	INSTALLED=${?}

  # Check exit code
	if [ ${INSTALLED} != 0 ]; then
    # Not installed. Add package name into the list.
		PACKAGES_TO_INSTALL+=(${PACKAGE})
	fi

}
export -f add_to_install_if_missing

################################################################################
#
# Install basic packages
#
function apt_install_basic_packages {

  state_set "${FUNCNAME[0]}" 'started'

  # Check dependencies
  local DEPENDENCIES=(
    "add_to_install_if_missing"
    "apt_install"
    "apt_update"
    "apt_upgrade"
    "assert_clean_exit"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # Update apt index and installed components, before installing additional packages.
  assert_clean_exit apt_update
  assert_clean_exit apt_upgrade

  # Define list of all required packages (by category, comment why we need the package for non-obvious ones)
  local REQUIRED_PACKAGES=(
      apt-utils # apt-utils required to avoid error: debconf: delaying package configuration, since apt-utils is not installed
      apt-transport-https # APT transport for downloading via the HTTP Secure protocol (HTTPS)
      software-properties-common # Part of "apt": manage the repositories that you install software from 3rd party repos (i.e. add their repo + gpg key)

      # The GNU Core Utilities are the basic file, shell and text manipulation utilities of the GNU operating system.
      # These are the core utilities which are expected to exist on every operating system.
      coreutils

      # Curl must exist for this script and many others
      curl

      # The ff_bash_functions require jq
      jq

      # This script requires grep
      grep

      # Docker requires these
      gnupg2
      lsb-release

      # System: CA certificates
      ca-certificates # Common CA certificates - Docker requires

      # For generate_strong_password (which uuencode is part of)
      sharutils
  )
  local MISSING_PACKAGES=()

  # Iterate required packages and collect only missing ones
  for REQUIRED_PACKAGE in "${REQUIRED_PACKAGES[@]}"; do
    add_to_install_if_missing ${REQUIRED_PACKAGE} MISSING_PACKAGES
  done

  # Install only missing packages
  apt_install ${MISSING_PACKAGES[@]} || { state_set "${FUNCNAME[0]}" 'error_failed_apt_install'; return 1; }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f apt_install_basic_packages

################################################################################
#
# Install set of basic packages (most installed by "apt", but some installed by
# different means (example: docker, n, npm, nodejs)), bash functions, .bashrc and .profile files.
#
function assert_baseline_components {
  state_set "${FUNCNAME[0]}" 'started'

  # Install basic packages before installing anything else. This will install "curl", thus "state_set" will be able to POST JSON.
  assert_clean_exit apt_install_basic_packages

  # Install NTP and make sure timesyncd is disabled (not working in parallel)
  # assert_clean_exit replace_timesyncd_with_ntpd

  # Ensure file "ff_agent/.profile" created and sourced from ~/.bashrc (Note: this must be done before install node)
  assert_clean_exit ff_agent_install_bashrc

  # Install nodejs suite and all its fixings (not using "apt") (Note: this will modify ff_agent/.profile)
  assert_clean_exit install_nodejs_suite

  # Install pm2
  assert_clean_exit pm2_ensure

  # Install npm package "@ff/ff_agent"
  assert_clean_exit ff_agent_install

  # Install scripts to manage ff_agent (update, logs, restart). Note: must be done after ff_agent installed, because ff_agent is dependency for them.
  assert_clean_exit ff_agent_scripts_install

  # Run ff_agent by pm2
  assert_clean_exit ff_agent_run_pm2

  # Register ff_agent in systemd
  assert_clean_exit ff_agent_register_pm2_systemd

  state_set "${FUNCNAME[0]}" 'success'
}
export -f assert_baseline_components

################################################################################
#
# Assert core credentials (npmrc, docker, ...)
#
function assert_core_credentials {
    state_set "${FUNCNAME[0]}" 'started'

    # [Q] We should be part of docker group. That's about it I think.
    # [A] Nope, we don't install docker as a 'baseline' environment, thus assection of core credentials will
    #     only take care of user being part of the 'docker group' in case corresponding environment was installed.

    state_set "${FUNCNAME[0]}" 'success'
}
export -f assert_core_credentials

################################################################################
#
# Install npm package "@ff/ff_agent" to FF_AGENT_HOME globally.
#
function ff_agent_install {
  state_set "${FUNCNAME[0]}" 'started'

  # Check dependencies
  local DEPENDENCIES=(
    "abort"
    "apt_install"
    "command_exists"
    "hardware_architecture_get"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # Define the version of ff_agent npm package to install from CDN
  VERSION='latest'

  local ARCHITECTURE=$( hardware_architecture_get ) || { state_set "${FUNCNAME[0]}" "error_getting_hardware_architecture"; return 1; }

  # If we are on arm64, we likely need to install some extra packages
  # This is done as a case, just in case we have other such architectural changes for other architectures.
  case "${ARCHITECTURE}" in
    arm64 | amd64)
      PACKAGES_TO_INSTALL=(
        libcurl4-openssl-dev
        build-essential
      )
      apt_install ${PACKAGES_TO_INSTALL[@]} || {
          state_set "${FUNCNAME[0]}" 'terminal_error_unable_to_ff_agent_install_dependencies'
          abort "${FUNCNAME[0]}" 'terminal_error_unable_to_ff_agent_install_dependencies'
        }
    ;;
    *)
    ;;
  esac

  # Install ff_agent
  # Previously we tried to install from CDN: npm install --global "${FF_CONTENT_URL}/ff/npm/ff-ff_agent-${VERSION}
  npm install --global @ff/ff_agent@${VERSION} || {
    state_set "${FUNCNAME[0]}" 'failed_to_ff_agent_install'
    abort "${FUNCNAME[0]}" 'failed_to_ff_agent_install'
  }

  # Ensure ff_agent is installed in the PATH
  command_exists ff_agent || {
    state_set "${FUNCNAME[0]}" 'terminal_error_unable_to_find_ff_agent'
    abort "${FUNCNAME[0]}" 'terminal_error_unable_to_find_ff_agent'
  }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f ff_agent_install

################################################################################
# CATEGORY
#   AGENT INSTALLATION FUNCTIONS
#
# NAME
#   ff_agent_install_bashrc - Ensure ff_agent environment is sourced from bash init files.
#
# SYNOPSIS
#   ff_agent_install_bashrc
#
# DESCRIPTION
#   Ensures proper shell environment initialization for ff_agent by injecting
#   sourcing logic into both the user's `.bashrc` and `.profile`, as well as
#   a dedicated ff_agent `.profile` located in ${FF_AGENT_HOME}.
#
#   The function performs the following steps:
#     - Verifies required environment variables (FF_AGENT_USERNAME, FF_AGENT_HOME) are set.
#     - Validates that ${FF_AGENT_HOME} exists.
#     - Creates missing `.bashrc` or `.profile` files if necessary.
#     - Injects a line to source ${FF_AGENT_HOME}/.profile into `.bashrc` and `.profile`.
#     - Injects a line into the ff_agent `.profile` to source the shared `ff_bash_functions` library.
#     - Injects a call to `discover_environment` into the ff_agent `.profile`.
#     - Injects the ff_agent `bin` directory into the `PATH` in the custom profile.
#     - Updates the current shell’s `PATH` variable if the bin path was not already present.
#
#   Each modification uses `inject_into_file` to ensure idempotent updates, preventing duplicate entries.
#
# DEPENDENCIES
#   - ensure_variable_not_empty
#   - state_set
#   - error
#   - abort
#   - inject_into_file
#   - discover_environment (called in profile)
#
# REQUIRED ENVIRONMENT VARIABLES
#   - FF_AGENT_USERNAME : Username under which ff_agent is installed
#   - FF_AGENT_HOME     : Root directory of the ff_agent installation
#
# USAGE EXAMPLE
#   ff_agent_install_bashrc
#
# EXIT STATUS
#   Aborts or returns non-zero on:
#     - Missing or empty required environment variables
#     - Missing ${FF_AGENT_HOME} directory
#     - Failure to create or modify any targeted profile/init file
#     - Failure to update the PATH variable
#   Returns 0 on successful injection of all profile customizations.
#
################################################################################
function ff_agent_install_bashrc {
  state_set "${FUNCNAME[0]}" 'started'

  # Check dependencies
  local DEPENDENCIES=(
    "abort"
    "discover_environment"
    "ensure_variable_not_empty"
    "error"
    "inject_into_file"
    "state_set"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # Define required non-empty variables
  local REQUIRED_NON_EMPTY_VARIABLES=(
    "FF_AGENT_USERNAME"
    "FF_AGENT_HOME"
    "HOME"
  )
  ensure_variables_not_empty "${FUNCNAME[0]}" "${REQUIRED_NON_EMPTY_VARIABLES[@]}" || { # Note: ensure_variables_not_empty will report missing variables
    state_set "${FUNCNAME[0]}" 'ensure_variables_not_empty_failed'
    return 1
  }

  # Make sure ${FF_AGENT_HOME} folder exists
  if [ ! -d "${FF_AGENT_HOME}" ]; then
    # ${FF_AGENT_HOME} folder is missing. Don't try to create it (it is not our responsibility)
    # Report an error and abort.
    state_set "${FUNCNAME[0]}" 'terminal_error_ff_agent_home_folder_does_not_exist'
    abort "${FUNCNAME[0]}" "FF_AGENT_HOME='${FF_AGENT_HOME}' directory Does not exist. Aborting."
  fi

  # Define location of two profile files
  local HOME_PROFILE_FILE="${HOME}/.profile"
  local FF_AGENT_PROFILE_FILE="${FF_AGENT_HOME}/.profile"    # example: /home/ubuntu/ff_agent/.profile  (Note: FF_AGENT_PROFILE_FILE is not local, but shell environment used in other install functions)

  # Define location of .bashrc file
  local HOME_BASHRC_FILE="${HOME}/.bashrc"

  # --------------------------------------------------------------------
  # Inject sourcing ff_agent/.profile into files:
  TARGET_FILES=( "${HOME_BASHRC_FILE}" "${HOME_PROFILE_FILE}" )

  # Iterate target files
  for TARGET_FILE in "${TARGET_FILES[@]}"; do
    # Create TARGET_FILE if missing
    if [ ! -f "${TARGET_FILE}" ]; then
      (
        cat <<EOT
# File ${TARGET_FILE} created by set_environment ${FUNCNAME[0]}() on $(date --utc).
EOT
      ) > "${TARGET_FILE}" || { state_set "${FUNCNAME[0]}" "failed_to_create_file"; return 1; }
    fi

    PATTERN="^source \"${FF_AGENT_PROFILE_FILE}\""
    INJECT_CONTENT=$(
      cat <<EOT
# Sourcing ${FF_AGENT_PROFILE_FILE} injected by set_environment ${FUNCNAME[0]}() on $(date --utc).
source "${FF_AGENT_PROFILE_FILE}"
EOT
    )
    ERROR_CODE='error_injecting_source_custom_profile'

    # Do injection and check result
    inject_into_file "${TARGET_FILE}" "${PATTERN}" "${INJECT_CONTENT}" || { state_set "${FUNCNAME[0]}" "${ERROR_CODE}"; return 1; }
  done
  #
  # --------------------------------------------------------------------

  # --------------------------------------------------------------------
  # Inject sourcing ff_bash_functions

  # Define path to the installed ff_bash_functions
  local FF_BASH_FUNCTIONS_PATH="${FF_AGENT_HOME}/git/redwolfsecurity/set_environment/src/ff_bash_functions"

  # Inject into the custom .profile to source ff_bash_functions (if missing)
  # Search expected line
  TARGET_FILE="${FF_AGENT_PROFILE_FILE}"
  PATTERN="^source \"${FF_BASH_FUNCTIONS_PATH}"
  INJECT_CONTENT=$(
    cat <<EOT
# Sourcing bash functions library from ${FF_BASH_FUNCTIONS_PATH} injected by set_environment ${FUNCNAME[0]}() on $(date --utc).
source "${FF_BASH_FUNCTIONS_PATH}"
EOT
  )
  ERROR_CODE='error_injecting_source_ff_bash_functions'

  # Create TARGET_FILE if missing
  if [ ! -f "${TARGET_FILE}" ]; then
    (
      cat <<EOT
# File ${TARGET_FILE} created by set_environment ${FUNCNAME[0]}() on $(date --utc).
EOT
    ) > "${TARGET_FILE}" || { state_set "${FUNCNAME[0]}" "failed_to_create_file"; return 1; }
  fi

  # Do injection and check result
  inject_into_file "${TARGET_FILE}" "${PATTERN}" "${INJECT_CONTENT}" || { state_set "${FUNCNAME[0]}" "${ERROR_CODE}"; return 1; }
  #
  # --------------------------------------------------------------------

  # --------------------------------------------------------------------
  # Inject call to "discover_environment" into the custom .profile
  TARGET_FILE="${FF_AGENT_PROFILE_FILE}"
  PATTERN="^discover_environment"
  INJECT_CONTENT=$(
      cat <<EOT
discover_environment
EOT
  )
  ERROR_CODE='error_injecting_discover_environment_call_to_custom_profile'

  # Do injection and check result
  inject_into_file "${TARGET_FILE}" "${PATTERN}" "${INJECT_CONTENT}" || { state_set "${FUNCNAME[0]}" "${ERROR_CODE}"; return 1; }
  #
  # --------------------------------------------------------------------

  # --------------------------------------------------------------------
  # Inject ${FF_AGENT_BIN} into PATH in .profile and modify current PATH if needed.

  # Define the path to ff_agent/bin folder, which we will inject into PATH
  local FF_AGENT_BIN="${FF_AGENT_HOME}/bin"

  # Update PATH variable (if it not yet contains expected string)
  printenv PATH | grep --quiet "${FF_AGENT_BIN}"
  if [ ${?} -ne 0 ]; then
    export PATH="${FF_AGENT_BIN}:${PATH}" || { state_set "${FUNCNAME[0]}" 'error_modifying_path'; return 1; }
  fi

  TARGET_FILE="${FF_AGENT_PROFILE_FILE}"
  PATTERN="^export PATH=\"${FF_AGENT_BIN}"
  INJECT_CONTENT=$(
      cat <<EOT
export PATH="${FF_AGENT_BIN}:\${PATH}"
EOT
  )
  ERROR_CODE='error_injecting_ff_agent_bin_path_to_custom_profile'

  # Do injection and check result
  inject_into_file "${TARGET_FILE}" "${PATTERN}" "${INJECT_CONTENT}" || { state_set "${FUNCNAME[0]}" "${ERROR_CODE}"; return 1; }
  #
  # --------------------------------------------------------------------

  # Chage state and return success
  state_set "${FUNCNAME[0]}" 'success'
}
export -f ff_agent_install_bashrc

################################################################################
# CATEGORY
#   AGENT CONTROL FUNCTIONS
#
# NAME
#   ff_agent_logs_flush_install - Install helper script to flush ff_agent logs via pm2.
#
# SYNOPSIS
#   ff_agent_logs_flush_install
#
# DESCRIPTION
#   Creates a script at ${FF_AGENT_HOME}/bin/ff_agent_logs_flush that, when executed,
#   calls `pm2 flush ff_agent` to clear logs for the ff_agent service.
#
# DEPENDENCIES
#   - pm2
#   - chmod
#   - abort
#   - state_set
#
# USAGE EXAMPLE
#   ff_agent_logs_flush_install
#
# EXIT STATUS
#   Non-zero on failure to create or chmod the script.
#
################################################################################
function ff_agent_logs_flush_install {
  state_set "${FUNCNAME[0]}" 'started'

  # Ensure required variables are set
  ensure_variables_not_empty "${FUNCNAME[0]}" "FF_AGENT_HOME" || { # Note: ensure_variables_not_empty will report missing variables
    state_set "${FUNCNAME[0]}" 'ensure_variables_not_empty_failed'
    return 1
  }

  local TARGET_FILE="${FF_AGENT_HOME}/bin/ff_agent_logs_flush"

  # Generate target script
  (
  # Note: this here-doc will be expanded
  cat <<EOT
#!/usr/bin/bash --login

# This script flushes @ff/ff_agent pm2 logs.
# It was generated by set_environment -> ${FUNCNAME[0]}() on $(date --utc).
EOT
  # Note: this here-doc will NOT be expanded (safe to use '$' without escaping it)
  cat <<'EOT'

state_set "ff_agent_logs_flush" 'started'

pm2 flush ff_agent || {
  state_set "ff_agent_logs_flush" "pm2_flush_failed"
  abort "${FUNCNAME[0]}" "Failed to flush logs for ff_agent"
}

state_set "ff_agent_logs_flush" 'success'
EOT
  ) > "${TARGET_FILE}" || {
    state_set "${FUNCNAME[0]}" "failed_to_create_file"
    return 1
  }

  # Make executable
  chmod a+x "${TARGET_FILE}" || {
    state_set "${FUNCNAME[0]}" "failed_to_chmod_file"
    return 1
  }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f ff_agent_logs_flush_install

################################################################################
# CATEGORY
#   AGENT CONTROL FUNCTIONS
#
# NAME
#   ff_agent_logs_show_install - Install helper script to tail ff_agent logs via pm2.
#
# SYNOPSIS
#   ff_agent_logs_show_install
#
# DESCRIPTION
#   Creates a script at ${FF_AGENT_HOME}/bin/ff_agent_logs_show that shows the
#   real-time logs for the ff_agent service using `pm2 logs ff_agent`.
#
# DEPENDENCIES
#   - pm2
#   - chmod
#   - state_set
#
# USAGE EXAMPLE
#   ff_agent_logs_show_install
#
# EXIT STATUS
#   Non-zero on failure to create or chmod the script.
#
################################################################################
function ff_agent_logs_show_install {
  state_set "${FUNCNAME[0]}" 'started'

  # Ensure required variables are set
  ensure_variables_not_empty "${FUNCNAME[0]}" "FF_AGENT_HOME" || { # Note: ensure_variables_not_empty will report missing variables
    state_set "${FUNCNAME[0]}" 'ensure_variables_not_empty_failed'
    return 1
  }

  local TARGET_FILE="${FF_AGENT_HOME}/bin/ff_agent_logs_show"

   # Generate target script
   (
  # Note: this here-doc will be expanded
  cat <<EOT
#!/usr/bin/bash --login

# This script tails @ff/ff_agent logs using pm2.
# It was generated by set_environment -> ${FUNCNAME[0]}() on $(date --utc).
EOT
  # Note: this here-doc will NOT be expanded (safe to use '$' without escaping it)
  cat <<'EOT'

state_set "ff_agent_logs_show" 'started'

pm2 logs ff_agent || {
  state_set "ff_agent_logs_show" "pm2_logs_failed"
  abort "${FUNCNAME[0]}" "Failed to show logs for ff_agent"
}

state_set "ff_agent_logs_show" 'success'
EOT
  ) > "${TARGET_FILE}" || {
    state_set "${FUNCNAME[0]}" "failed_to_create_file"
    return 1
  }

  chmod a+x "${TARGET_FILE}" || {
    state_set "${FUNCNAME[0]}" "failed_to_chmod_file"
    return 1
  }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f ff_agent_logs_show_install

################################################################################
# CATEGORY
#   AGENT CONTROL FUNCTIONS
#
# NAME
#   ff_agent_register_pm2_systemd - Register pm2 to launch on boot using systemd.
#
# SYNOPSIS
#   ff_agent_register_pm2_systemd
#
# DESCRIPTION
#   Ensures that pm2 is configured to start automatically on system boot using
#   systemd for the ff_agent user. The function first verifies that systemd is
#   present and running as PID 1, skipping the setup if systemd is unavailable
#   (e.g., inside containers or minimal environments).
#
#   If systemd is detected, it configures the pm2 startup service for the
#   ff_agent user using the appropriate command and enables the corresponding
#   systemd unit (`pm2-${USER}`).
#
# DEPENDENCIES
#   - state_set
#   - abort
#   - command_exists
#   - command_run_as_user
#   - systemd (must be PID 1)
#   - pm2
#
# USAGE EXAMPLE
#   ff_agent_register_pm2_systemd
#
# EXIT STATUS
#   If systemd is not detected, sets state to 'systemd_not_detected' and exits with 0.
#   On failure to configure or enable pm2 systemd startup, sets state and aborts.
#   Returns 0 on successful registration and enablement of pm2 startup under systemd.
#
################################################################################
function ff_agent_register_pm2_systemd {
  state_set "${FUNCNAME[0]}" 'started'

  # Check if we are running inside docker (have systemd)
  command_exists systemctl &>/dev/null || {
    state_set "${FUNCNAME[0]}" 'systemd_not_detected'
    return 0                     # systemctl not installed
  }

  [[ "$(ps -p 1 -o comm= 2>/dev/null)" == "systemd" ]] || {
    state_set "${FUNCNAME[0]}" 'systemd_process_not_detected'
    return 0        # PID 1 must be systemd
  }

  # Ensuring pm2 startup works on boot for ${FF_AGENT_USERNAME}
  command_run_as_user "${FF_AGENT_USERNAME}" 'sudo env PATH=$PATH:${FF_AGENT_HOME}/.n/bin pm2 startup systemd -u ${USER} --hp ${HOME}' || {
    state_set "${FUNCNAME[0]}" 'terminal_error_unable_to_ff_agent_register_pm2_systemd'
    abort "${FUNCNAME[0]}" "Failed to ensure pm2 startup works on boot for ${FF_AGENT_USERNAME}"
  }

  # Enable systemd unit
  command_run_as_user "${FF_AGENT_USERNAME}" 'sudo systemctl enable pm2-${USER}' || {
    state_set "${FUNCNAME[0]}" 'terminal_error_unable_to_ff_agent_register_pm2_systemd'
    abort "${FUNCNAME[0]}" "Failed to ensure pm2 startup works on boot for ${FF_AGENT_USERNAME}"
  }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f ff_agent_register_pm2_systemd

################################################################################
# CATEGORY
#   AGENT CONTROL FUNCTIONS
#
# NAME
#   ff_agent_restart_install - Install helper script to restart ff_agent via pm2.
#
# SYNOPSIS
#   ff_agent_restart_install
#
# DESCRIPTION
#   Creates a script at ${FF_AGENT_HOME}/bin/ff_agent_restart that restarts
#   the ff_agent process using `pm2 restart ff_agent --update-env`.
#
# DEPENDENCIES
#   - pm2
#   - chmod
#   - state_set
#
# USAGE EXAMPLE
#   ff_agent_restart_install
#
# EXIT STATUS
#   Non-zero on failure to create or chmod the script.
#
################################################################################
function ff_agent_restart_install {
  state_set "${FUNCNAME[0]}" 'started'

  ensure_variables_not_empty "${FUNCNAME[0]}" "FF_AGENT_HOME" || { # Note: ensure_variables_not_empty will report missing variables
    state_set "${FUNCNAME[0]}" 'ensure_variables_not_empty_failed'
    return 1
  }

  local TARGET_FILE="${FF_AGENT_HOME}/bin/ff_agent_restart"

   # Generate target script
   (
  # Note: this here-doc will be expanded
  cat <<EOT
#!/usr/bin/bash --login

# This script restarts @ff/ff_agent using pm2.
# It was generated by set_environment -> ${FUNCNAME[0]}() on $(date --utc).
EOT
  # Note: this here-doc will NOT be expanded (safe to use '$' without escaping it)
  cat <<'EOT'

state_set "ff_agent_restart" 'started'

pm2 restart ff_agent --update-env || {
  state_set "ff_agent_restart" "pm2_restart_failed"
  abort "${FUNCNAME[0]}" "Failed to restart ff_agent"
}

state_set "ff_agent_restart" 'success'
EOT
  ) > "${TARGET_FILE}" || {
    state_set "${FUNCNAME[0]}" "failed_to_create_file"
    return 1
  }

  chmod a+x "${TARGET_FILE}" || {
    state_set "${FUNCNAME[0]}" "failed_to_chmod_file"
    return 1
  }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f ff_agent_restart_install

################################################################################
# CATEGORY
#   AGENT CONTROL FUNCTIONS
#
# NAME
#   ff_agent_run_pm2 - Start the ff_agent process using pm2 if not already running.
#
# SYNOPSIS
#   ff_agent_run_pm2
#
# DESCRIPTION
#   Ensures that the ff_agent binary is available in the PATH, then registers and
#   starts it via pm2 using the correct user context. The function checks whether
#   ff_agent is already managed by pm2 and skips the start step if it is. After
#   starting, it verifies that ff_agent is actually running under pm2.
#
# DEPENDENCIES
#   - command_exists
#   - state_set
#   - abort
#   - command_run_as_user
#   - pm2
#
# USAGE EXAMPLE
#   ff_agent_run_pm2
#
# EXIT STATUS
#   Sets state and exits via `abort` on any critical error.
#   Otherwise returns 0 on success.
#
################################################################################
function ff_agent_run_pm2 {
  state_set "${FUNCNAME[0]}" 'started'

  # Check dependencies
  local DEPENDENCIES=(
    "command_run_as_user"
    "ff_agent"
    "jq"
    "pm2"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # Define required non-empty variables
  local REQUIRED_NON_EMPTY_VARIABLES=(
    "FF_AGENT_USERNAME"
  )
  ensure_variables_not_empty "${FUNCNAME[0]}" "${REQUIRED_NON_EMPTY_VARIABLES[@]}" || { # Note: ensure_variables_not_empty will report missing variables
    state_set "${FUNCNAME[0]}" 'ensure_variables_not_empty_failed'
    return 1
  }

  # Try to get status of ff_agent from pm2 using JSON
  local PM2_STATUS
  PM2_STATUS=$(pm2 jlist | jq -r '.[] | select(.name=="ff_agent") | .pm2_env.status')

  if [[ -z "${PM2_STATUS}" ]]; then
    log "${FUNCNAME[0]}" "[INFO] ff_agent is not registered in pm2. Starting it..."
    command_run_as_user "${FF_AGENT_USERNAME}" 'pm2 start node --name ff_agent -- ff_agent' || {
      state_set "${FUNCNAME[0]}" 'failed_to_start_ff_agent'
      abort "${FUNCNAME[0]}" 'failed_to_start_ff_agent'
    }
  fi

  if [[ "${PM2_STATUS}" != "online" ]]; then
    log "${FUNCNAME[0]}" "[INFO] ff_agent is registered but not running (status=${PM2_STATUS}). Restarting it..."
    command_run_as_user "${FF_AGENT_USERNAME}" 'pm2 restart ff_agent' || {
      state_set "${FUNCNAME[0]}" 'failed_to_restart_ff_agent'
      abort "${FUNCNAME[0]}" 'failed_to_restart_ff_agent'
    }
  else
    log "${FUNCNAME[0]}" "[INFO] ff_agent is already running under pm2."
  fi

  # Save current pm2 process list
  pm2 save || {
    state_set "${FUNCNAME[0]}" 'failed_to_pm2_save'
    abort "${FUNCNAME[0]}" 'failed_to_pm2_save'
  }

  # Double-check that ff_agent status (must be "online" now)
  PM2_STATUS=$(pm2 jlist | jq -r '.[] | select(.name=="ff_agent") | .pm2_env.status')
  if [ "${PM2_STATUS}" != "online" ]; then
    state_set "${FUNCNAME[0]}" 'ff_agent_not_running_after_start'
    abort "${FUNCNAME[0]}" 'ff_agent_not_running_after_start'
  fi

  state_set "${FUNCNAME[0]}" 'success'
}
export -f ff_agent_run_pm2


################################################################################
# Orchestritor function: calls ff_agent relsted scripts instllers
function ff_agent_scripts_install {
  state_set "${FUNCNAME[0]}" 'started'

  # Install a script to flush ff_agent logs
  assert_clean_exit ff_agent_logs_flush_install

  # Install a script to show ff_agent logs
  assert_clean_exit ff_agent_logs_show_install

  # Install a script to restart ff_agent
  assert_clean_exit ff_agent_restart_install

  # Install a script to update and restart ff_agent
  assert_clean_exit ff_agent_update_install

  state_set "${FUNCNAME[0]}" 'success'
}
export -f ff_agent_scripts_install

################################################################################
# CATEGORY
#   AGENT CONTROL FUNCTIONS
#
# NAME
#   ff_agent_update_install - Generate an update script for ff_agent that reinstalls and restarts it via pm2.
#
# SYNOPSIS
#   ff_agent_update_install
#
# DESCRIPTION
#   Ensures that the ff_agent binary is available in the PATH, then generates a
#   reusable update script (`ff_agent_update`) under the ${FF_AGENT_HOME}/bin directory.
#   This script, when executed, performs the following actions:
#
#     - Verifies environment integrity using set_environment_is_working.
#     - Installs a specific version of @ff/ff_agent globally using npm.
#     - Outputs the version of the installed package.
#     - Flushes the pm2 logs via ff_agent_logs_flush script.
#     - Restarts the ff_agent process via ff_agent_restart script.
#
#   The generated script includes error handling and state setting for each step.
#   After the script is created, this function ensures it is marked as executable.
#
# DEPENDENCIES
#   - command_exists
#   - state_set
#   - abort
#   - ensure_variables_not_empty
#   - set_environment_is_working (runtime in generated script)
#   - npm
#   - pm2
#   - chmod
#   - bash (must support here-docs)
#
# USAGE EXAMPLE
#   ff_agent_update_install
#
# EXIT STATUS
#   Sets state and aborts if ff_agent is not found in PATH.
#   Sets state and returns non-zero on failure to create or chmod the script.
#   Returns 0 on successful script generation and setup.
#
################################################################################
function ff_agent_update_install {
  state_set "${FUNCNAME[0]}" 'started'

  # Check dependencies
  local DEPENDENCIES=("ff_agent")
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # Validate required non-empty variables
  local REQUIRED_NON_EMPTY_VARIABLES=("FF_AGENT_HOME")
  ensure_variables_not_empty "${FUNCNAME[0]}" "${REQUIRED_NON_EMPTY_VARIABLES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'ensure_variables_not_empty_failed'
    return 1
  }

  # Create update script target
  local TARGET_FILE="${FF_AGENT_HOME}/bin/ff_agent_update"

  # Generate ff_agent_update script via here-doc
  (
  # Note: this here-doc will be expanded
  cat <<EOT
#!/usr/bin/bash --login

# This script updates @ff/ff_agent and restarts it using pm2.
# It was generated by set_environment -> ${FUNCNAME[0]}() on $(date --utc).
EOT
  # Note: this here-doc will NOT be expanded (safe to use '$' without escaping it)
  cat <<'EOT'

state_set "ff_agent_update" 'started'

# Check set_environment is working
set_environment_is_working || {
  # Note" we can not use state_set / abort here.
  echo "ff_agent_update" "set_environment_is_working() failed." 1>&2
  exit 1
}

# Install @ff/ff_agent
npm install --global @ff/ff_agent@${VERSION} || {
  state_set "ff_agent_update" "npm_install_ff_agent_failed"
  abort "${FUNCNAME[0]}" "ff_agent_update" "Failed to npm install @ff/ff_agent@${VERSION}"
}

# Log installed version of @ff/ff_agent
FF_AGENT_VERSION=$(cat ${FF_AGENT_HOME}/.n/lib/node_modules/@ff/ff_agent/package.json | grep '"version"')
log "Installed @ff/ff_agent version: '${FF_AGENT_VERSION}'"

# Flush logs using predefined script
ff_agent_logs_flush || {
  state_set "ff_agent_update" "ff_agent_logs_flush_flush_failed"
  abort "ff_agent_update" "Failed to flush logs"
}

# Restart the service using predefined script
ff_agent_restart || {
  state_set "ff_agent_update" "restart_failed"
  abort "ff_agent_update" "Failed to restart ff_agent"
}

state_set "ff_agent_update" 'success'
EOT
  ) > "${TARGET_FILE}" || {
    state_set "${FUNCNAME[0]}" "failed_to_create_file"
    return 1
  }

  # Make the generated script executable
  chmod a+x "${TARGET_FILE}" || {
    state_set "${FUNCNAME[0]}" "failed_to_chmod_file"
    return 1
  }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f ff_agent_update_install

################################################################################
# CATEGORY
#   SYSTEM SETUP FUNCTIONS
#
# NAME
#   install_authbind - Install and configure authbind for privileged ports
#
# SYNOPSIS
#   install_authbind
#
# DESCRIPTION
#   Installs the `authbind` package and configures port-level access permissions
#   so non-root processes can bind to privileged ports (<=1024), such as 80 and 443.
#
#   This function performs the following steps:
#     - Ensures `authbind` is installed
#     - Ensures configuration files exist for ports 80 and 443 in /etc/authbind/byport/
#     - Applies proper permissions and ownership to those files
#
#   It skips any step that is already completed and is safe to re-run (idempotent).
#
#   Once configured, you can run a binary (or symlink) with elevated bind privileges.
#   Note: the path to the executable can be a symlink.
#     Example:
#       sudo authbind --deep /opt/ff_agent/bin/ff_agent_start
#
#     This grants permission to bind ports like 80/443 without running as root,
#     provided the binary internally performs the binding itself (not via subprocess).
#
# DEPENDENCIES
#   - apt_install
#   - chmod
#   - chown
#   - command_exists
#   - state_set
#
# USAGE EXAMPLE
#   install_authbind
#
# EXIT STATUS
#   Returns 0 on successful install or if already configured
#   Returns 1 on error, setting appropriate state
#
################################################################################
function install_authbind {
  state_set "${FUNCNAME[0]}" 'started'

  # Check dependencies
  local DEPENDENCIES=(
    "apt_install"
    "chmod"
    "chown"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # Install authbind if missing
  if ! command_exists authbind; then
    apt_install authbind || {
      state_set "${FUNCNAME[0]}" 'failed_to_install_authbind'
      return 1
    }
  fi

  # Define list of ports to configure
  local PORTS=(80 443)
  for PORT in "${PORTS[@]}"; do
    local FILE="/etc/authbind/byport/${PORT}"

    # Create file if it doesn't exist
    if [[ ! -f "${FILE}" ]]; then
      sudo touch "${FILE}" || {
        state_set "${FUNCNAME[0]}" "failed_to_create_authbind_byport_${PORT}"
        return 1
      }
    fi

    # Set restrictive permissions if not already 500
    if [[ "$(stat -c '%a' "${FILE}")" != "500" ]]; then
      sudo chmod 500 "${FILE}" || {
        state_set "${FUNCNAME[0]}" "failed_to_set_permission_authbind_byport_${PORT}"
        return 1
      }
    fi

    # Set ownership to root:root if not already
    if [[ "$(stat -c '%U:%G' "${FILE}")" != "root:root" ]]; then
      sudo chown root:root "${FILE}" || {
        state_set "${FUNCNAME[0]}" "failed_to_set_ownership_authbind_byport_${PORT}"
        return 1
      }
    fi
  done

  state_set "${FUNCNAME[0]}" 'success'
}
export -f install_authbind

################################################################################
#
# Function installs "go" by certain version (see below) if it is not already installed.
#
# In case of successful install (or already at expected version) script return success code 0.
# In case of any errors script prints error to standard error stream and exit with code 1.
#
function install_go {
  state_set "${FUNCNAME[0]}" 'started'

  # Check dependencies
  local DEPENDENCIES=(
    "command_exists"
    "curl"
    "hardware_architecture_get"
    "inject_into_file"
    "is_writable"
    "mktemp"
    "os_name_get"
    "tar"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # Define required non-empty variables
  local REQUIRED_NON_EMPTY_VARIABLES=(
    "FF_AGENT_HOME"
  )
  ensure_variables_not_empty "${FUNCNAME[0]}" "${REQUIRED_NON_EMPTY_VARIABLES[@]}" || { # Note: ensure_variables_not_empty will report missing variables
    state_set "${FUNCNAME[0]}" 'ensure_variables_not_empty_failed'
    return 1
  }

  # Get the latest available version number. Note: the url below now returns 2 lines,
  # 1st with version (example: go1.21.0)
  # 2nd useless line that breaks it if not supressed (example: time 2023-08-04T20:14:06Z)
  local URL="https://go.dev/VERSION?m=text"
  local EXPECTED_VERSION=$( url_get "${URL}" '-' | head -n1 )

  # Check status of 1st command in the excuted bove pipeline
  if [ ${PIPESTATUS[0]} -ne 0 ]; then
    state_set "${FUNCNAME[0]}" 'failed_to_get_latest_version_number'
    return 1
  fi

  [ ! -z "${EXPECTED_VERSION}" ] || { state_set "${FUNCNAME[0]}" 'failed_to_get_latest_version_number'; return 1; }

  # Check if go is already installed and has expected vesrion
  if command_exists go >/dev/null; then
      # Yes, 'go' is installed. Check if installed version matches expected one.
      INSTALLED_VERSION="$( go version )" || { state_set "${FUNCNAME[0]}" 'failed_to_get_existing_version_number'; return 1; }

      # Compare to expected version
      if [[ "${INSTALLED_VERSION}" =~ ${EXPECTED_VERSION} ]]; then
        # Match. Version is up to date, nothing to do.
        state_set "${FUNCNAME[0]}" 'success'
        return 0
      fi
      # Version mismatch, simply continue installation (to upgrade)...
  fi

  # Create temporary folder (for downloading 'go' archive)
  local TEMP_DIR="$( mktemp --directory )" || { state_set "${FUNCNAME[0]}" 'failed_to_create_temp_dir'; return 1; }

  # Check temporary folder created and we can write to it
  if ! is_writable "${TEMP_DIR}"; then
    state_set "${FUNCNAME[0]}" "error_temp_dir_is_not_writable"
    return 1
  fi

  # Get OS
  local OS="$( os_name_get )" || { state_set "${FUNCNAME[0]}" "failed_to_os_name_get"; return 1; }
  [ ! -z "${OS}" ] || { state_set "${FUNCNAME[0]}" "failed_to_os_name_get"; return 1; }

  # Get ARCHITECTURE
  local ARCHITECTURE="$( hardware_architecture_get )" || { state_set "${FUNCNAME[0]}" "failed_to_hardware_architecture_get"; return 1; }
  [ ! -z "${OS}" ] || { state_set "${FUNCNAME[0]}" "failed_to_hardware_architecture_get"; return 1; }

  # Define archive filename
  TARBALL_FILENAME="${EXPECTED_VERSION}.${OS}-${ARCHITECTURE}.tar.gz"

  # Download archive
  URL="https://go.dev/dl/${TARBALL_FILENAME}"
  curl \
    --silent    \
    --retry 5    \
    --location    \
    --retry-delay 1 \
    --retry-max-time 60 \
    --max-time 185 \
    --connect-timeout 12 \
    -o "${TEMP_DIR}/${TARBALL_FILENAME}" \
    "${URL}" || { state_set "${FUNCNAME[0]}" "failed_to_download_archive"; return 1; }

  # Check if file downloaded (in case of "404 not found" curl return code 0 and will not create "-o file")
  [ -f "${TEMP_DIR}/${TARBALL_FILENAME}" ] || { state_set "${FUNCNAME[0]}" "failed_to_download_archive"; return 1; }

  # Remove previous local version of 'go' if exists
  # 1st "blind assumption" to remove go from expected place
  if [ -d "${FF_AGENT_HOME}/go" ]; then
    rm -fr "${FF_AGENT_HOME}/go" || { state_set "${FUNCNAME[0]}" "failed_to_remove_existing_go"; return 1; }
  fi
  # 2nd remove "go" if it is in the path
  if command_exists go >/dev/null; then
      # Yes, 'go' is installed.
      local EXISTING_GO_FILEPATH=$(command_exists go)
      sudo rm "${EXISTING_GO_FILEPATH}"
  fi
  # Also noted other locations! Must improve "remove go" functionality to cleanup these as well:
  # /usr/bin/go -> ../lib/go-1.13/bin/go
  # /usr/lib/go -> go-1.13/

  # Install 'go'

  # Unzip downloaded archive (the "bin" folder of the golang will be available here: ${FF_AGENT_HOME}/go/bin/ )
  tar -C "${FF_AGENT_HOME}" -xzf "${TEMP_DIR}/${TARBALL_FILENAME}" || { state_set "${FUNCNAME[0]}" "failed_to_extract_archive"; return 1; }

  # Remove temporary folder
  rm -fr "${TEMP_DIR}" || { error "Warning: failed to remove temporary folder: '${TEMP_DIR}'"; }

  # Define the path to ff_agent profile file (we need to add a path to 'go' into ff_agent/.profile if missing)
  TARGET_FILE="${FF_AGENT_HOME}/.profile"

  # Create TARGET_FILE if does not exist and add a comment (who/when creaeted it)
  if [ ! -f "${TARGET_FILE}" ]; then
    (
      cat <<EOT
# File ${TARGET_FILE} created by set_environment ${FUNCNAME[0]}() on $( date --utc ).
EOT
    ) > "${TARGET_FILE}" || { state_set "${FUNCNAME[0]}" "failed_to_create_file"; return 1; }
  fi

  # Check if expected line was already injected into the profile.
  # Note: it is not too specific, it is exactly the line that must be present in the ff_agent custom profille file.
  PATTERN="^export PATH=\${PATH}:${FF_AGENT_HOME}/go/bin"
  INJECT_CONTENT=$(
    cat <<EOT
# The path to 'go' inserted by $( pwd )/$( basename ${0} ) on $( date --utc )'
export PATH=\${PATH}:${FF_AGENT_HOME}/go/bin
EOT
  )
  ERROR_CODE='error_injecting_source_custom_profile'

  # Inject and check result code
  inject_into_file  \
    "${TARGET_FILE}" \
    "${PATTERN}" \
    "${INJECT_CONTENT}" || { state_set "${FUNCNAME[0]}" "${ERROR_CODE}"; return 1; }

  # Also inject path to 'go' into current PATH (if missing in PATH)
  # do the export, so we don't have to relogin in order to call "go version"
  echo ${PATH} | grep --quiet ${FF_AGENT_HOME}/go/bin
  if [ ${?} -ne 0 ]; then
    # Path to 'go' is missing from PATH environment variable. Inject it:
    export PATH=${PATH}:${FF_AGENT_HOME}/go/bin
  fi

  # Check installed 'go' version
  INSTALLED_VERSION="$( go version )" || { state_set "${FUNCNAME[0]}" 'failed_to_get_installed_version_number'; return 1; }

  # Compare to the expected version
  if [[ "${INSTALLED_VERSION}" =~ ${EXPECTED_VERSION} ]]; then
    # Good - expected version installed.
    state_set "${FUNCNAME[0]}" 'success'
    return 0
  else
    # Mismatch.
    state_set "${FUNCNAME[0]}" 'failed_to_match_expected_vs_installed_version'
    return 1
  fi
}
export -f install_go

################################################################################
#
# Installations of "n" based on the tutorial:
#  "Getting started with n (node version management)"
#   https://zacharytodd.com/posts/n-version-manager/
#
#
# Require environment variables set:
#   - FF_AGENT_HOME
#
# Official n github page:
#   https://github.com/tj/n
#   https://github.com/tj/n#installation
#
function install_n {
  state_set "${FUNCNAME[0]}" "start"

  # Check dependencies
  local DEPENDENCIES=(
    "curl"
    "inject_into_file"
    "popd"
    "printenv"
    "pushd"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # Define required non-empty variables
  local REQUIRED_NON_EMPTY_VARIABLES=(
    "FF_AGENT_HOME"
  )
  ensure_variables_not_empty "${FUNCNAME[0]}" "${REQUIRED_NON_EMPTY_VARIABLES[@]}" || { # Note: ensure_variables_not_empty will report missing variables
    state_set "${FUNCNAME[0]}" 'ensure_variables_not_empty_failed'
    return 1
  }

  # Define path to ff_agent .profile
  local FF_AGENT_PROFILE_FILE="${FF_AGENT_HOME}/.profile"    # example: /home/ubuntu/ff_agent/.profile  (Note: FF_AGENT_PROFILE_FILE is not local, but shell environment used in other install functions)

  # Check custom .profile file exists
  if [ ! -f "${FF_AGENT_PROFILE_FILE}" ]; then
    # Let's not try to re-create it if missing.
    # It should have been created by existing ff_agent_install_bashrc()
  	state_set "${FUNCNAME[0]}" "error_custom_ff_agent_profile_does_not_exist"
    return 1
  fi

  # Create tmp folder and change directory into it
  TMPDIR="$( mktemp -d )"
  pushd "${TMPDIR}" || { state_set "${FUNCNAME[0]}" 'error_pushd_to_tmp_directory'; return 1; }

  # Attempt 1: download 'n' from FF_CONTENT_URL
  # Try FF_CONTENT_URL first because it gives more control over what version of 'n' will be executed.
  # The magour update on the github might introduce some breaking change, let's leave it for 2nd attept only.
  SAVE_AS='n'
  URL="${FF_CONTENT_URL}/ff/ff_agent/hotpatch/hotpatch_files/${SAVE_AS}"
  curl \
    --silent    \
    --retry 5    \
    --location    \
    --retry-delay 1 \
    --retry-max-time 60 \
    --max-time 55 \
    --connect-timeout 12 \
    -o "${SAVE_AS}" \
    "${URL}"

  # Check curl exit code
  if [ ${?} -ne 0 ]; then
      state_set "${FUNCNAME[0]}" 'failed_to_download_n_from_content_server'

      # Attempt 2: download 'n' from from github
      URL="https://raw.githubusercontent.com/tj/n/master/bin/n"
      curl \
        --silent    \
        --retry 5    \
        --location    \
        --retry-delay 1 \
        --retry-max-time 60 \
        --max-time 55 \
        --connect-timeout 12 \
        -o "${SAVE_AS}" \
        "${URL}"

      # Check curl exit code
      if [ ${?} -ne 0 ]; then
        # The 2nd attempt failed too, giving up.
        # Error: clean up tmp folder, report an error and return error code 1
        popd || { state_set "${FUNCNAME[0]}" 'error_popd'; return 1; }
        rm -fr "${TMPDIR}" || { state_set "${FUNCNAME[0]}" 'failed_to_remove_tmpdir'; return 1; }
        state_set "${FUNCNAME[0]}" 'warning_failed_to_download_n_from_github'
        return 1
      fi
  fi

  # Export 2 env variables we need for "n" to operate properly:  and NODE_PATH

  # ------------------ Export N_PREFIX and inject that export into FF_AGENT_PROFILE_FILE (begin) ----------------
  export N_PREFIX="${FF_AGENT_HOME}/.n"  # example: /home/ubuntu/ff_agent/.n

  # Add '# Export N_PREFIX' into the custom .profile file if in was not injected earlier.
  TARGET_FILE="${FF_AGENT_PROFILE_FILE}"
  PATTERN="^export N_PREFIX=\"${FF_AGENT_HOME}/.n\""
  EXPECTED_LINE="export N_PREFIX=\"${FF_AGENT_HOME}/.n\""
  INJECT_CONTENT=$(
  cat <<EOT
# N_PREFIX environment injected by set_environment ${FUNCNAME[0]} on $(date --utc)
${EXPECTED_LINE}
EOT
  )
  ERROR_CODE='error_injecting_export_n_prefix_to_ff_agent_profile'

  # Do injection and check result
  inject_into_file  \
    "${TARGET_FILE}" \
    "${PATTERN}" \
    "${INJECT_CONTENT}" || {
      # Error: clean up tmp folder, report an error and return error code 1
      popd || { state_set "${FUNCNAME[0]}" 'error_popd'; return 1; }
      rm -fr "${TMPDIR}" || { state_set "${FUNCNAME[0]}" 'failed_to_remove_tmpdir'; return 1; }
      state_set "${FUNCNAME[0]}" "${ERROR_CODE}"
      return 1
  }

  # ------------------ Export N_PREFIX and inject that export into FF_AGENT_PROFILE_FILE (begin) ----------------


  # ------------------ Export NODE_PATH and inject that export into FF_AGENT_PROFILE_FILE (begin) ----------------
  # We set NODE_PATH, so npm can load modules. Details: https://stackoverflow.com/questions/12594541/npm-global-install-cannot-find-module
  export NODE_PATH="${FF_AGENT_HOME}/.n/lib/node_modules"

  # Add '# Export NODE_PATH' into the custom .profile file if in was not injected earlier.
  TARGET_FILE="${FF_AGENT_PROFILE_FILE}"
  PATTERN="^export NODE_PATH=\"${FF_AGENT_HOME}/.n/lib/node_modules\""
  EXPECTED_LINE="export NODE_PATH=\"${FF_AGENT_HOME}/.n/lib/node_modules\""
  INJECT_CONTENT=$(
  cat <<EOT
# Injected by set_environment ${FUNCNAME[0]} on $(date --utc)
${EXPECTED_LINE}
EOT
  )
  ERROR_CODE='error_injecting_export_node_path_to_ff_agent_profile'

  # Do injection and check result
  inject_into_file  \
    "${TARGET_FILE}" \
    "${PATTERN}" \
    "${INJECT_CONTENT}" || {
      # Error: clean up tmp folder, report an error and return error code 1
      popd || { state_set "${FUNCNAME[0]}" 'error_popd'; return 1; }
      rm -fr "${TMPDIR}" || { state_set "${FUNCNAME[0]}" 'failed_to_remove_tmpdir'; return 1; }
      state_set "${FUNCNAME[0]}" "${ERROR_CODE}"
      return 1
  }
  # ------------------ Export NODE_PATH and inject that export into FF_AGENT_PROFILE_FILE (end) ----------------


  # ------------------ Inject "ff_agent/.n/bin" into PATH and inject that export into FF_AGENT_PROFILE_FILE (begin) ----------------

  # Update PATH variable (if it not yet contains expected string)
  printenv PATH | grep --quiet "${N_PREFIX}/bin"
  if [ ${?} -ne 0 ]; then
    export PATH="${N_PREFIX}/bin:${PATH}" || {
        # Error: clean up tmp folder, report an error and return error code 1
        popd || { state_set "${FUNCNAME[0]}" 'error_popd'; return 1; }; rm -fr "${TMPDIR}"  || { state_set "${FUNCNAME[0]}" 'failed_to_remove_tmpdir'; return 1; }
        state_set "${FUNCNAME[0]}" 'error_modifying_path'; return 1;
    }
  fi

  # Note: we escape "\$" in front of the PATH, so it does not get expanded
  TARGET_FILE="${FF_AGENT_PROFILE_FILE}"
  PATTERN="^export PATH=\"${N_PREFIX}/bin:\${PATH}\""
  EXPECTED_LINE="export PATH=\"${N_PREFIX}/bin:\${PATH}\""
  if ! file_contains_pattern "${TARGET_FILE}" "${PATTERN}"; then
    # Expected line is missing, Inject text
    (
      cat <<EOT
# Injected by set_environment ${FUNCNAME[0]} on $(date --utc)
${EXPECTED_LINE}
EOT
    ) >> "${TARGET_FILE}" || {
        # Error: clean up tmp folder, report an error and return error code 1
        popd || { state_set "${FUNCNAME[0]}" 'error_popd'; return 1; }; rm -fr "${TMPDIR}"  || { state_set "${FUNCNAME[0]}" 'failed_to_remove_tmpdir'; return 1; }
        state_set "${FUNCNAME[0]}" 'error_injecting_n_prefix_bin_to_ff_agent_profile'; return 1;
    }
  fi
  # ------------------ Inject "ff_agent/.n/bin" into PATH and inject that export into FF_AGENT_PROFILE_FILE (end) ----------------

  #
  VERSION=$( nodejs_desired_version_get )
  [ -z "${VERSION}" ] && { state_set "${FUNCNAME[0]}" 'failed_to_nodejs_desired_version_get'; abort 'failed_to_nodejs_desired_version_get'; }

  # Install 'n_lts' using dowloaded into TMPDIR 'n' ('n_lts' will be installed into ff_agent/.n)
  retry_command 5 15 bash n "${VERSION}" || {
    # Error: clean up tmp folder, report an error and return error code 1
    popd || { state_set "${FUNCNAME[0]}" 'error_popd'; return 1; }; rm -fr "${TMPDIR}"  || { state_set "${FUNCNAME[0]}" 'failed_to_remove_tmpdir'; return 1; }
    state_set "${FUNCNAME[0]}" 'error_installing_n'; return 1;
  }

  # Install 'n' into ff_agent/.n  (yes, we have downloaded 'n' into TMPDIR,
  # then used it to install 'npm', and now we use 'npm' to install "globally" n.
  # The proper installed 'n' will reisde under ff_agent/.n/ folder)
  npm install --verbose --global n || {
    # Error: clean up tmp folder, report an error and return error code 1
    popd || { state_set "${FUNCNAME[0]}" 'error_popd'; return 1; }; rm -fr "${TMPDIR}"  || { state_set "${FUNCNAME[0]}" 'failed_to_remove_tmpdir'; return 1; }
    state_set "${FUNCNAME[0]}" 'error_installing_n'; return 1;
  }

  # Clean up tmp folder
  popd || { state_set "${FUNCNAME[0]}" 'error_popd'; return 1; }; rm -fr "${TMPDIR}"  || { state_set "${FUNCNAME[0]}" 'failed_to_remove_tmpdir'; return 1; }

  # Chage state and return success
  state_set "${FUNCNAME[0]}" 'success'
}
export -f install_n

################################################################################
#
function install_nodejs {
  state_set "${FUNCNAME[0]}" 'started'

 # Check dependencies
  local DEPENDENCIES=(
    "install_n"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # Get desired nodejs version
  local VERSION="$( nodejs_desired_version_get )"
  [ -z "${VERSION}" ] && { state_set "${FUNCNAME[0]}" 'failed_to_nodejs_desired_version_get'; abort 'failed_to_nodejs_desired_version_get'; }


  # # We need to stop pm2 before replacing location of nodejs, otherwise any pm2 command would faild
  # stop_pm2
  # uninstall_n_outside_ff_agent_home  || { state_set "${FUNCNAME[0]}" 'terminal_error_uninstall_n_outside_ff_agent_home'; abort 'terminal_error_uninstall_n_outside_ff_agent_home'; }
  install_n || { state_set "${FUNCNAME[0]}" 'terminal_error_install_n'; abort 'terminal_error_install_n'; }
  n install "${VERSION}" || { state_set "${FUNCNAME[0]}" 'terminal_error_switching_node_version'; abort 'terminal_error_switching_node_version'; }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f install_nodejs

################################################################################
#
# Install nodejs latest environment
function install_nodejs_suite {
  state_set "${FUNCNAME[0]}" 'started'

 # Check dependencies
  local DEPENDENCIES=(
    "install_authbind"
    "install_nodejs"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # We want nodejs to be able to open ports 443 and 80, so we will install_authbind before this.

  install_authbind || { state_set "${FUNCNAME[0]}" 'install_authbind_failed'; abort 'install_authbind_failed'; }

  install_nodejs || { state_set "${FUNCNAME[0]}" 'terminal_error_install_node'; abort 'terminal_error_install_node'; }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f install_nodejs_suite

################################################################################
#
# Continuation of the "set_environment". Installing baseline components.
# On error: function aborts (so no need to errorcheck on caller side)
#
function install_set_environment_baseline {
  state_set "${FUNCNAME[0]}" 'started'

 # Check dependencies
  local DEPENDENCIES=(
    "abort"
    "assert_clean_exit"
    "discover_environment"
    "set_environment_ensure_ff_agent_bin_exists"
    "setup_logging"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # Discover environment (choose user, make sure it's home folder exists, check FF_CONTENT_URL is set etc.)
  discover_environment || abort "${FUNCNAME[0]}" "failed to discover_environment"

  # Now we can state_set()
  state_set "${FUNCNAME[0]}" 'started'

  # Put logs in best location
  setup_logging || { state_set "${FUNCNAME[0]}" "terminal_error_failed_to_setup_logging"; abort 'terminal_error_failed_to_setup_logging'; }

  # Ensure ff_agent/bin folder exists before assert_baseline_components
  set_environment_ensure_ff_agent_bin_exists || { state_set "${FUNCNAME[0]}" "terminal_error_failed_to_set_environment_ensure_ff_agent_bin_exists"; abort 'terminal_error_failed_to_set_environment_ensure_ff_agent_bin_exists'; }

  # Install set of basic packages, bash functions, .bashrc and .profile files
  assert_clean_exit assert_baseline_components || { state_set "${FUNCNAME[0]}" "terminal_error_failed_to_assert_baseline_components"; abort 'terminal_error_failed_to_assert_baseline_components'; }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f install_set_environment_baseline

# ##########################################################################################
# #
# # The following function defines the list of packages required to run "puppeteer" as a part
# # of unit tests on our porjects.
# # See the official "Puppeteer: Troubleshooting" page:
# # https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
# #
# ##########################################################################################
# function apt_install_puppeteer_dependencies {
#   local REQUIRED_PACKAGES=(
#     ca-certificates
#     fonts-liberation
#     libappindicator3-1
#     libasound2
#     libatk-bridge2.0-0
#     libatk1.0-0
#     libc6
#     libcairo2
#     libcups2
#     libdbus-1-3
#     libexpat1
#     libfontconfig1
#     libgbm1
#     libgcc1
#     libglib2.0-0
#     libgtk-3-0
#     libnspr4
#     libnss3
#     libpango-1.0-0
#     libpangocairo-1.0-0
#     libstdc++6
#     libx11-6
#     libx11-xcb1
#     libxcb1
#     libxcomposite1
#     libxcursor1
#     libxdamage1
#     libxext6
#     libxfixes3
#     libxi6
#     libxrandr2
#     libxrender1
#     libxss1
#     libxtst6
#     lsb-release
#     wget
#     xdg-utils
#   )
# }


# ###############################################################################
# #
# # install_ntp disables timesyncd and installs ntp if missing
# #
# # The systemd-timesyncd is basically a small client-only NTP implementation more or less bundled with newer systemd releases.
# # It's more lightweight than a full ntpd but only supports time sync - i.e. it can't act as an NTP server for other machines.
# # We should not use both in parallel, as in theory they could pick different timeservers that have a slight delay between them,
# # leading to your system clock being periodically "jumpy".
# #
# # Comparing the ntp and systemd-timesyncd I found out that ntpd is much better solution:
# # systemd-timesyncd does no clock discipline: the clock is not trained or compensated, and internal clock drift over time is not reduced.
# # It has rudimentary logic to adjust poll interval but without disciplining the host will end up with uneven time forever as
# # systemd-timesyncd pushes or pulls at whatever interval it thinks the near-term drift requires. It also can't assess the
# # quality of the remote time source. You're unlikely to get accuracy much greater than 100ms. This is sufficient for simple
# # end user devices like laptops, but it could definitely cause problems for distributed systems that want greater time precision.
# # (source article: https://unix.stackexchange.com/questions/305643/ntpd-vs-systemd-timesyncd-how-to-achieve-reliable-ntp-syncing/464729#464729 )
# #
# # So install_ntp() disables "systemd-timesyncd" and leaves only "ntpd".
# #
# # Return value: 0 = success, 1 = failure
# #
# # Note: f-n also uses state_set()
# #
# function replace_timesyncd_with_ntpd {
#     state_set "${FUNCNAME[0]}" 'started'

#     # Check if timesyncd is active (disable if active)
#     IS_TIMESYNCD_ACTIVE=$( systemctl status systemd-timesyncd.service | grep -i active | awk '{print $2}' )  # returns 'active' or 'inactive'

#     # Have to commend out the "if" statement below. Here's the reason why:
#     #   Noted IBM agents, where "timedatectl status" still reports non-ntpd time syncing is in place: "Network time on: yes"
#     #   BUT AT THE SAME TIME the "systemctl status systemd-timesyncd.service" output shows "Active: inactive (dead)"
#     #   and only after we run "sudo timedatectl set-ntp no" the output of "timedatectl status" will be finally expected: "Network time on: no"
#     #
#     #if [ "${IS_TIMESYNCD_ACTIVE}" == "active" ]; then

#         # timesyncd is active, need to deactivate it:
#         sudo timedatectl set-ntp no

#         # make sure timedatectl is not not active
#         IS_TIMESYNCD_ACTIVE=$( systemctl status systemd-timesyncd.service | grep -i active | awk '{print $2}' )  # returns 'active' or 'inactive'
#         if [ "${IS_TIMESYNCD_ACTIVE}" == "active" ]; then
#             # Still active! Error out
#             state_set "${FUNCNAME[0]}" 'failed_stop_timesyncd'
#             return 1
#         fi

#     #fi

#     # Check if ntpd is insatalled (install if missing)
#     IS_NTP_INSTALLED=$( dpkg --get-selections ntp | grep -v deinstall | grep install | awk '{print $2}' )  # returns 'install' if is installed or emptry string if not
#     if [ "${IS_NTP_INSTALLED}" != "install" ]; then
#         # ntp is not installed, install it
#         apt_install ntp

#         # Check if ntp is now installed
#         IS_NTP_INSTALLED=$( dpkg --get-selections ntp | grep -v deinstall | grep install | awk '{print $2}' )  # returns 'install' if is installed or emptry string if not
#         if [ "${IS_NTP_INSTALLED}" != "install" ]; then
#             # Still not isntalled! Error out
#             state_set "${FUNCNAME[0]}" 'failed_to_install_ntp'
#             return 1
#         fi
#     fi

#     # Enble NTP (this will make it to autostart on reboot)
#     sudo systemctl enable ntp
#     if [ ${?} -ne 0 ]; then
#         state_set "${FUNCNAME[0]}" 'failed_to_enable_ntp'
#     fi

#     # Start NTP (note: it is safe to try to start in case it is already running - this might happen if ntp was not installed and was just added 1st time by apt)
#     sudo systemctl start ntp
#     if [ ${?} -ne 0 ]; then
#         state_set "${FUNCNAME[0]}" 'failed_to_start_ntp'
#     fi

#     # Last status check: query local ntpd
#     LOCAL_NTP_QUERY_STATUS=$( ntpq -pn )
#     LOCAL_NTP_QUERY_STATUS_EXIT_CODE=${?}

#     if [ ${LOCAL_NTP_QUERY_STATUS_EXIT_CODE} -ne 0 ]; then
#         state_set "${FUNCNAME[0]}" 'failed_to_query_ntp'
#         return 1
#     fi

#     state_set "${FUNCNAME[0]}" 'success'
#     return 0
# }

################################################################################
# Category: process
# pm2_configure
# Configures pm2 the way we want it configured
function pm2_configure {
    state_set "${FUNCNAME[0]}" 'started'

    # Define dependencies
    local DEPENDENCIES=(
      "timeout"
      "seq"
      "pm2"
    )
    check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
      state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
      return 1
    }

    # Now it is installed, and command is in path. So we shall configure it
    # Configure it to automatically save state
    timeout 30 pm2 set pm2:autodump true            || { state_set "${FUNCNAME[0]}" "pm2_configure_autodump_error"; return 1; }

    # Configure it to rotate logs
    timeout 45 pm2 install pm2-logrotate            || { state_set "${FUNCNAME[0]}" "pm2_install_logrotate_error"; return 1; }
    timeout 30 pm2 set pm2-logrotate:max_size 20M   || { state_set "${FUNCNAME[0]}" "pm2_configure_logrotate_error"; return 1; }
    timeout 30 pm2 set pm2-logrotate:retain 7       || { state_set "${FUNCNAME[0]}" "pm2_configure_logrotate_error"; return 1; }
    timeout 30 pm2 set pm2-logrotate:compress true  || { state_set "${FUNCNAME[0]}" "pm2_configure_logrotate_error"; return 1; }

    # configure it to rotate logs every hour
    timeout 30 pm2 set pm2-logrotate:rotateInterval '0 0 * * * *'  || { state_set "${FUNCNAME[0]}" "pm2_configure_logrotate_error"; return 1; }

    # pm2 update sometimes fail on 1st attempt, but then works on the 2nd. Let's add 3 attempts to make sure.
    local IS_PM2_UPDATED=false MAX_ATTEMPTS=3 ATTEMPT
    for ATTEMPT in $( seq 1 ${MAX_ATTEMPTS} ); do
      timeout 55 pm2 update && { IS_PM2_UPDATED=true; break; }
    done
    [ "${IS_PM2_UPDATED}" == "true" ] || { state_set "${FUNCNAME[0]}" "pm2_update_error"; return 1; } # "Error: failed to update pm2 after ${ATTEMPT} attempts"

    state_set "${FUNCNAME[0]}" 'success'
}
export -f pm2_configure

################################################################################
# Category: process
# pm2_ensure
# This ensures that pm2 is running, and working as we wish. aborts otherwise.
# If it is not installed, we install it.
function pm2_ensure {
    state_set "${FUNCNAME[0]}" 'started'

    # Define dependencies
    local DEPENDENCIES=(
      "abort"
      "pm2_configure"
      "pm2_is_running_as_me"
      "pm2_is_installed"
      "pm2_install"
      "pm2_start"
    )
    check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
      state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
      return 1
    }

    # If pm2 is running, then we ensure it is properly configured. It might have been running already, but not properly configured.
    pm2_is_running_as_me
    if [ ${?} == 0 ]; then
        pm2_configure || { state_set "${FUNCNAME[0]}" 'error_configuring_pm2'; abort 'error_configuring_pm2'; }
        state_set "${FUNCNAME[0]}" 'success'
        return 0
    fi

    # It is not running as me, it might not be installed. If that's the case, we install it.
    # Is pm2 installed? If not, install it
    pm2_is_installed || pm2_install || { state_set "${FUNCNAME[0]}" 'error_failed_to_install_pm2'; abort 'error_failed_to_install_pm2'; }

    # Now it has to at least be installed, and not running, so we try to start it.
    pm2_start || { state_set "${FUNCNAME[0]}" 'failed_to_start_pm2'; abort 'failed_to_start_pm2'; }

    # Check if pm2 started and running by expected user
    pm2_is_running_as_me || { state_set "${FUNCNAME[0]}" 'error_pm2_not_running_as_user'; abort 'error_pm2_not_running_as_user'; }

    # Now it is running, so let's configure it
    pm2_configure || { state_set "${FUNCNAME[0]}" 'error_configuring_pm2'; abort 'error_configuring_pm2'; }

    # If all above works, we have it running
    state_set "${FUNCNAME[0]}" 'success'
}
export -f pm2_ensure

################################################################################
# Category: process
# pm2_install
# Will install pm2 if there is no command 'pm2'
# Will not start it
function pm2_install {
    state_set "${FUNCNAME[0]}" 'started'

    # Define dependencies
    local DEPENDENCIES=(
      "command_exists"
    )
    check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
      state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
      return 1
    }

    local NPM_PACKAGE="pm2"
    local VERSION="latest"

    # Commented out, since stop_pm2() does not exist (was removed as empty function). If you want to kill that daemon process then run command
    # "pm2 kill" instead of trying to use f-n stop_pm(). Also then update f-n comments to say that this f-n stops pm2 if it is already installed.
    #
    # # We will try to stop it. But that won't stop us from uninstalling it.
    # pm2_is_running_as_me && stop_pm2

    local PM2=$( command_exists "${NPM_PACKAGE}" )
    [ "${PM2}" != "" ] && { state_set "${FUNCNAME[0]}" 'success_no_action_already_installed'; return 0; }

    local NPM=$( command_exists npm )
    [ "${NPM}" == "" ] && { state_set "${FUNCNAME[0]}" 'error_dependency_not_met_npm'; return 1; }

    # Actually install it -- globally
    ${NPM} install --global "${NPM_PACKAGE}@${VERSION}"  || { state_set "${FUNCNAME[0]}" 'error_installing_pm2_npm'; return 1; }

    # Verify command actually exists in path after we have installed it
    local PM2=$( command_exists "${NPM_PACKAGE}" )
    [ "${PM2}" == "" ] && { state_set "${FUNCNAME[0]}" 'error_installing_pm2_command_not_found'; return 1; }

    state_set "${FUNCNAME[0]}" 'success'
}
export -f pm2_install

################################################################################
# Category: process
# pm2_is_installed
# Checks if pm2 is installed
# Returns 0 if it is, 1 if it isn't
function pm2_is_installed {
  # Check dependencies
  local DEPENDENCIES="command_exists"
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES}" || return 1  # Note: check_dependencies will report missing dependencies

  # Return 0 if command exists
  command_exists pm2 >/dev/null
}
export -f pm2_is_installed

################################################################################
# Category: process
# pm2_is_running_as_me
# Will return 0 if it is, 1 if it is not
function pm2_is_running_as_me {
    state_set "${FUNCNAME[0]}" 'started'

    # Define dependencies
    local DEPENDENCIES=(
      "process_is_running_as_me"
    )
    check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
      state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
      return 1
    }

    # Process will look like PM2 v4.5.5: God Daemon (/home/user/.pm2)
    local PATTERN="PM2 .*: God Daemon"

    # Check if process is running as local user.
    process_is_running_as_me "${PATTERN}"
    local STATUS=${?}

    state_set "${FUNCNAME[0]}" 'success'

    return ${STATUS}
}
export -f pm2_is_running_as_me

################################################################################
# Category: process
# pm2_start
function pm2_start {
    state_set "${FUNCNAME[0]}" 'started'

    # Define dependencies
    local DEPENDENCIES=(
      "command_exists"
      "pm2"
      "pm2_is_running_as_me"
    )
    check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
      state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
      return 1
    }

    # Check if it is running. If it is, we're happy.
    pm2_is_running_as_me && { state_set "${FUNCNAME[0]}" 'success_no_action_pm2_is_running'; return 0; }

    local PM2=$( command_exists pm2 )
    [ -z "${PM2}" ] && { state_set "${FUNCNAME[0]}" 'error_dependency_not_met_pm2_command'; return 1; }
    "${PM2}" start

    # Check if it is running. If it is, we're happy.
    # Note: pm2 can start and still return non-zero (i.e. it started but there was no ecosystem.config.js
    # So it is not sufficient to test for return code, but if it is running as me, then it is at least started
    pm2_is_running_as_me && { state_set "${FUNCNAME[0]}" 'success'; return 0; }

    state_set "${FUNCNAME[0]}" 'failed_to_pm2_start'
}
export -f pm2_start

################################################################################
# Category: process
# pm2_stop stops the running pm2 daemon running as the current user.
# does not stop any root level or other user pm2 daemons.
#
function pm2_stop {
    state_set "${FUNCNAME[0]}" 'started'

    # Define dependencies
    local DEPENDENCIES=(
      "command_exists"
      "pm2"
      "pm2_is_running_as_me"
    )
    check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
      state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
      return 1
    }

    # Check if it is running. If it isn't, we finish.
    pm2_is_running_as_me || { state_set "${FUNCNAME[0]}" 'success_no_action_pm2_not_running'; return 0; }

    # Check if we have the pm2 command. We need it to be able to stop pm2
    local PM2=$( command_exists pm2 ) || { state_set "${FUNCNAME[0]}" 'error_pm2_command_not_found'; return 1; }

    # Try and kill pm2
    # Todo: do this with timeout - sometimes pm2 hangs. We ask it to kill itself, but sometimes the cat comes back :)
    "${PM2}" kill || { state_set "${FUNCNAME[0]}" 'error_pm2_kill_failed'; return 1; }

    # Verify that it is actually stopped. If it is still running after we killed it, it is a problem.
    pm2_is_running_as_me || { state_set "${FUNCNAME[0]}" 'error_unable_to_validate_pm2_daemon_gone_postcondition_pm2_still_running'; return 1; }

    # We have stopped it, and it is not running.
    state_set "${FUNCNAME[0]}" 'success'
}
export -f pm2_stop

################################################################################
# Category: process
# pm2_uninstall
# Removes PM2
function pm2_uninstall {
    state_set "${FUNCNAME[0]}" 'started'

    # Define dependencies
    local DEPENDENCIES=(
      "command_exists"
      "pm2_is_installed"
    )
    check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
      state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
      return 1
    }

    local PACKAGE="pm2"

    # If it is not installed, we are done.
    pm2_is_installed || { state_set "${FUNCNAME[0]}" 'success_no_action_not_installed'; return 0; }

    # It's installed, so we will try to remove it
    local NPM=$( command_exists npm )
    [ "${NPM}" = "" ] && { state_set "${FUNCNAME[0]}" 'error_dependency_not_met_npm'; return 1; }
    "${NPM}" remove --global "${PACKAGE}" || { state_set "${FUNCNAME[0]}" 'error_uninstalling_package'; return 1; }

    # Verify it is removed. If this returns 1, it is not found. If it returns 0, we still have it.
    pm2_is_installed || { state_set "${FUNCNAME[0]}" 'success'; return 0; }

    state_set "${FUNCNAME[0]}" 'error_validating_uninstallation'
}
export -f pm2_uninstall

################################################################################
#
# Function makes sure "${FF_AGENT_HOME}/bin" folder is created.
#
function set_environment_ensure_ff_agent_bin_exists {

  state_set "${FUNCNAME[0]}" 'started'

  # Define dependencies
  local DEPENDENCIES=(
    "ensure_variable_not_empty"
    "mkdir"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }


  # Loop through dependencies
  for DEPENDENCY in "${DEPENDENCIES[@]}"; do
    if ! command_exists "${DEPENDENCY}"; then
      error "${FUNCNAME[0]}" "error_dependency_not_met_${DEPENDENCY}"
      state_set "${FUNCNAME[0]}" "error_dependency_not_met_${DEPENDENCY}"
      return 1
    fi
  done

  # Define required non-empty variables
  local REQUIRED_NON_EMPTY_VARIABLES=(
    "FF_AGENT_HOME"
  )
  ensure_variables_not_empty "${FUNCNAME[0]}" "${REQUIRED_NON_EMPTY_VARIABLES[@]}" || { # Note: ensure_variables_not_empty will report missing variables
    state_set "${FUNCNAME[0]}" 'ensure_variables_not_empty_failed'
    return 1
  }


  # Define target directory
  TARGET_DIR="${FF_AGENT_HOME}/bin"

  # Check if target directory exists
  [ -d "${TARGET_DIR}" ] || {
    # Does not exist. Create new.
    mkdir -p "${TARGET_DIR}" || { state_set "${FUNCNAME[0]}" 'failed_to_create_directory'; return 1; }
  }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f set_environment_ensure_ff_agent_bin_exists

################################################################################
#
# Function makes sure the symlink "set_environment_install" exists in the ${FF_AGENT_HOME}/bin/ folder.
# If symlink is missing it will be created:
#    ${FF_AGENT_HOME}/bin/set_environment_install -> ${FF_AGENT_HOME}/git/redwolfsecurity/set_environment/install
# The installed command "set_environment_install" can also be run to update set_environment.
#
function set_environment_ensure_install_exists {

  state_set "${FUNCNAME[0]}" 'started'

 # Check dependencies
  local DEPENDENCIES=(
    "ln"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # Define required non-empty variables
  local REQUIRED_NON_EMPTY_VARIABLES=(
    "FF_AGENT_HOME"
  )
  ensure_variables_not_empty "${FUNCNAME[0]}" "${REQUIRED_NON_EMPTY_VARIABLES[@]}" || { # Note: ensure_variables_not_empty will report missing variables
    state_set "${FUNCNAME[0]}" 'ensure_variables_not_empty_failed'
    return 1
  }

  # Define symlink
  SYMLINK="${FF_AGENT_HOME}/bin/set_environment_install"

  # Define target file (which new symlink must point to)
  TARGET_FILE="${FF_AGENT_HOME}/git/redwolfsecurity/set_environment/install"

  # Check symlink exists. Note: -L returns true if the "file" exists and is a symbolic link (the linked file may or may not exist).
  [ -L "${SYMLINK}" ] || {
      # SYMLINK is missing. Try to create new symlink.
      ln -s "${TARGET_FILE}" "${SYMLINK}" || { state_set "${FUNCNAME[0]}" 'failed_to_create_symlink'; return 1; }
  }

  # Check the target file is present (symlink is not broken)
  [ -f "${TARGET_FILE}" ] || { state_set "${FUNCNAME[0]}" 'error_target_file_missing'; return 1; }

  # Check the target file is executable. Note: extra "-f" check added here since "-x" can say "yes, executable", but target points to directory.
  [[ -f "${TARGET_FILE}" && -x "${TARGET_FILE}" ]] || { state_set "${FUNCNAME[0]}" 'error_target_file_not_executable'; return 1; }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f set_environment_ensure_install_exists

################################################################################
#
# Function set_environment_preserve_source_code require the only argument: root folder of the project
# from which the installer was started. It will analyze if the installer was started
# from the expected place (ff_agent/git/[companyname]/set_environment/ folder) and if not
# it will preserve source code into appropriate folder for future use (updates etc.).
#
function set_environment_preserve_source_code {
  state_set "${FUNCNAME[0]}" 'started'

 # Check dependencies
  local DEPENDENCIES=(
    "github_repository_url_parse"
    "grep"
    "mkdir"
    "popd"
    "pushd"
    "ssh-keyscan"
  )
  check_dependencies "${FUNCNAME[0]}" "${DEPENDENCIES[@]}" || {  # Note: check_dependencies will report missing dependencies
    state_set "${FUNCNAME[0]}" 'dependencies_check_failed'
    return 1
  }

  # Define required non-empty variables
  local REQUIRED_NON_EMPTY_VARIABLES=(
    "FF_AGENT_HOME"
  )
  ensure_variables_not_empty "${FUNCNAME[0]}" "${REQUIRED_NON_EMPTY_VARIABLES[@]}" || { # Note: ensure_variables_not_empty will report missing variables
    state_set "${FUNCNAME[0]}" 'ensure_variables_not_empty_failed'
    return 1
  }

  # Get passed parameters (path to currently installed project folder)
  PROJECT_ROOT_DIR="${1}"
  [ -d "${PROJECT_ROOT_DIR}" ] || { state_set "${FUNCNAME[0]}" 'failed_to_set_environment_preserve_source_code'; return 1; }

  # As a preparation to preserve project source files (used during this installation), let's change directory to the project root directory.
  pushd "${PROJECT_ROOT_DIR}" || { state_set "${FUNCNAME[0]}" 'failed_to_cd_into_project'; return 1; }

  # We need to trust github.com to avoid errors like this:
  # The authenticity of host 'github.com (140.82.113.4)' can't be established.
  # This fix was found here:
  # https://gist.github.com/vikpe/34454d69fe03a9617f2b009cc3ba200b
  # https://github.com/ome/devspace/issues/38
  # And to avoid dublicates:
  # https://serverfault.com/questions/132970/can-i-automatically-add-a-new-host-to-known-hosts
  if ! grep --quiet "$(ssh-keyscan github.com 2>/dev/null)" ${HOME}/.ssh/known_hosts; then
    ssh-keyscan github.com >> ${FF_AGENT_USER_HOME}/.ssh/known_hosts
  fi

  # Extract project owner from github repository URL
  local URL=$( git remote show origin | grep 'Fetch URL:' | awk -F'Fetch URL: ' '{print $2}' )
  [ ! -z "${URL}" ] || { state_set "${FUNCNAME[0]}" 'failed_to_extract_project_url'; return 1; }

  local OWNER=$( github_repository_url_parse "${URL}" --owner )
  [ ! -z "${OWNER}" ] || { state_set "${FUNCNAME[0]}" 'failed_to_extract_project_owner'; return 1; }

  # All projects sources got preserved in this folder
  local PRESERVED_PROJECTS_DIR="${FF_AGENT_HOME}/git"

  # Define current project-specific name and preserved project-specific directory
  local PROJECT_NAME='set_environment'
  local PRESERVED_PROJECT_DIR="${PRESERVED_PROJECTS_DIR}/${OWNER}/${PROJECT_NAME}"

  # Make sure the project-specific folder exists
  if [ ! -d "${PRESERVED_PROJECT_DIR}" ]; then
    # Does not exist, try to create it
    mkdir -p "${PRESERVED_PROJECT_DIR}" || { state_set "${FUNCNAME[0]}" 'failed_to_create_folder_for_code_preservation'; return 1; }
  fi

  # Check PWD is set or try to use $(pwd) or error out
  if [ -z "${PWD}" ]; then
    # PWD is not set, try to set it by "pwd" call
    PWD="$( pwd )" || { state_set "${FUNCNAME[0]}" 'failed_to_get_pwd'; return 1; }
  fi

  # Check if installer running from unexpected folder
  # TODO: check if folder from which we're running installation contains spaces (e.g.: "/tmp/some folder with spaces/" )
  if [ "${PWD}" != "${PRESERVED_PROJECT_DIR}" ]; then
      # Current installer run from unexpected place (like some temporary folder) - need to preserve installed project source folder.
      # Check if previously preserved folder exists, then remove its content before copying files
      # (we don't want the preserved folder to be a mix/merge with old deleted files).
      if [ -d "${PRESERVED_PROJECT_DIR}" ]; then
          # Remove old project source folder content (leaving the folder itself)
          # Note: we don't rm -fr some/path/* since this would miss hidden files. The 'find' gets them all!
          find "${PRESERVED_PROJECT_DIR}" -mindepth 1 -delete || { state_set "${FUNCNAME[0]}" 'failed_to_remove_old_project_source_folder'; return 1; }
      fi

      # Copy newly installed source folder (to preserve it)
      # Note: the "/." is here to copy all files including hidden (which starts with dot). Just '*' would not work.
      cp -a "${PWD}/." "${PRESERVED_PROJECT_DIR}" || { state_set "${FUNCNAME[0]}" 'failed_to_preserve_source_folder'; return 1; }
  fi

  # Restore the original folder
  popd || { state_set "${FUNCNAME[0]}" 'failed_to_popd_after_preserving_source_folder'; return 1; }

  state_set "${FUNCNAME[0]}" 'success'
}
export -f set_environment_preserve_source_code

################################################################################
# Log this script standard output and standard error to a log file AND system logger
function set_script_logging {

  # Note: we can not yet call "state_set" on that early stages
 	#state_set "${FUNCNAME[0]}" 'started'

  # Let's find a good directory for logs. This assumes zero knowledge.
  # The _best_ place for these logs would be in "${HOME}/ff_agent/logs" -- if we can write to it we'll create it
  POTENTIAL_LOG_DIRECTORIES=( "${FF_AGENT_HOME}/logs" /var/log/ff_agent /tmp/ff_agent/logs /tmp/ff_agent.$$/logs )

  LOG_DIRECTORY=""

  # Find a directory we can write to. The first will do.
  for POTENTIAL_LOG_DIRECTORY in "${POTENTIAL_LOG_DIRECTORIES[@]}"
  do
      if mkdir -p "${POTENTIAL_LOG_DIRECTORY}"
      then
          LOG_DIRECTORY=${POTENTIAL_LOG_DIRECTORY}
          break
      fi
  done

  if [ -z "${LOG_DIRECTORY}" ]; then
      error "Unable to find a place to log! Tried: ${POTENTIAL_LOG_DIRECTORIES[@]}"
      export LOG_PATH=$( tty )
  else
      # Get current epoch ms. (note: we can't yet use   # "$( epoch_ms_get )" because ff_bash_functions arent installed/updated yet)
      TIMESTAMP_EPOCH_MS="$( epoch_ms_get )"
      LOG_FILE="set_environment.${TIMESTAMP_EPOCH_MS}.log"
      export LOG_PATH="${LOG_DIRECTORY}/${LOG_FILE}"
      # PREVIOUSLY THIS WAS exec &> >(tee -a "${LOG_PATH}")
      exec &> >(tee >(tee -a "${LOG_PATH}" | logger -t set_environment ))
  fi

  # Note: we can not yet call "state_set" on that early stages
 	#state_set "${FUNCNAME[0]}" 'success'
}
export -f set_script_logging

################################################################################
# Orchestrator function
function setup_logging {
  # Ensure script output sent to standard output and standard error to a log file AND system logger
	set_script_logging
}
export -f setup_logging
