#!/usr/bin/env bash

# Enable tracing (more verbose output)
set -x

# This script implements the installer logic of the "set_environment" project.
# Project github page: https://github.com/redwolfsecurity/set_environment
#
# Caller must source this script, so it can inject environment into the current terminal as well.
# To check the installation result one can use "set_environment_is_working" selfcheck function.
# If installation succeed then selfcheck function will return success code 0.
#
# Caller can check if set_environment was started by the right user (after sourcing ". ./install")
# by chkecking environment variable ${FF_AGENT_USERNAME}.
#      Example: if [ "${FF_AGENT_USERNAME}" == "$(whoami)" ]; then echo "I'm the right/proper user"; fi
#

# Set optional SERVICE variable. If it is set, then it will be used:
#  - as a tag for logger in log()
#  - to state_set() in abort() and successful_exit()
export SERVICE="set_environment"

###############################################################################
#
function install_set_environment {
    # Can't state_set() here yet
    # state_set "${FUNCNAME[0]}" 'started'

    # Change directory into the script's directory. This ensure all relative paths working correctly.
    cd "$( dirname $( readlink -f "${BASH_SOURCE[0]}" ) )" || { echo "Error: failed to change directory to $( dirname ${BASH_SOURCE[0]} )" >&2; exit 1; } # note: can not yet use error() / abort() / state_set()

    # Source common functions
    source src/ff_bash_functions || { echo "Error: failed to source common functions." >&2; exit 1; } # note: can not yet use error() / abort() / state_set()

    # Initialize terminal
    terminal_initialize || { state_set "${FUNCNAME[0]}" "terminal_error_initialize_terminal"; abort 'terminal_error_initialize_terminal'; }

    # Continue by calling OS-specific installer
    source "src/architecture/$( discover_os )/continue_install.sh" "${@}" || { state_set "${FUNCNAME[0]}" "terminal_error_continue_install"; abort 'terminal_error_continue_install'; }

    # Last step: run a selfcheck
    set_environment_is_working || { state_set "${FUNCNAME[0]}" "terminal_error_selfcheck_failed"; abort 'terminal_error_selfcheck_failed'; }

    state_set "${FUNCNAME[0]}" 'success'
}

install_set_environment  # no need to check errors here, the f-n itself reports errors (all of which are "terminal" errors) and aborts/exits.

set +x
