#!/usr/bin/env bash
# Install set_environment - Copyright (2018-2025) RedOKI

# Temporarily disable u (nounset)
set +u

# Do not run this script as root
[ "$EUID" -ne 0 ] || { echo "❌ Do not run this script as root." >&2; exit 1; }

# Enable tracing (more verbose output)
export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] [${FUNCNAME[0]:-MAIN}] '
set -x

# Set optional SERVICE variable. If it is set, then it will be used:
#  - as a tag for logger in log()
#  - to state_set() in abort() and successful_exit()
export SERVICE="set_environment"

###############################################################################
#
# This function dynamically gets the directory the script is running in
script_directory_get() {
  local SOURCE="${BASH_SOURCE[0]}"
  while [ -h "$SOURCE" ]; do
    local DIR
    DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"
    SOURCE="$(readlink "$SOURCE")"
    [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE"
  done
  cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd
}
export -f script_directory_get


###############################################################################
#
# shellcheck disable=SC2120
function install_set_environment () {
  # Bootstraping

  # Change directory into the script's directory. This ensure all relative paths working correctly.
  # TODO Error Check
  SET_ENVIRONMENT_SCRIPT_DIRECTORY="$( script_directory_get )"
  echo "🟧 top level install script directory is set to: ${SET_ENVIRONMENT_SCRIPT_DIRECTORY}"

  export SET_ENVIRONMENT_SCRIPT_DIRECTORY
  cd "${SET_ENVIRONMENT_SCRIPT_DIRECTORY}" || { echo "Error: failed to change directory to ${SET_ENVIRONMENT_SCRIPT_DIRECTORY}" >&2; exit 1; }

  # Source common functions
  source ./src/ff_bash_functions || { echo "Error: failed to source ff_bash_functions common functions." >&2; exit 1; }
  log "✅ sourced ff_bash_functions."

  # Create ff_agent home directories - THIS IS WHERE THE INSTALLER CREATES THE FIRST DIRECTORIES
  ## TODO: Error check and check what it outputs
  ff_agent_home_get_best
  export FF_AGENT_HOME
  [ -n "${FF_AGENT_HOME}" ] || { state_set "${FUNCNAME[0]}" "terminal_error_variable_ff_agent_home_not_set"; abort 'Failed to read FF_AGENT_HOME env var. ff_agent_home_get_best did not set it.'; }
  mkdir -p "${FF_AGENT_HOME}" || { state_set "${FUNCNAME[0]}" "terminal_error_cant_create_home_directory"; abort 'terminal_error_cant_create_home_directory'; }
  local DIR
  for DIR in bin state secrets applications git; do
      mkdir -p "${FF_AGENT_HOME}/${DIR}" || { state_set "${FUNCNAME[0]}" "terminal_error_cant_create_${DIR}_directory"; abort "terminal_error_cant_create_${DIR}_directory"; }
  done

  state_set "${FUNCNAME[0]}" 'started'

  # Initialize terminal
  terminal_initialize

  # Continue by calling OS-specific installer
  local OS
  OS="$( discover_os )"
  # TODO: Add error checks
  log "🟧 Discovered OS: ${OS}"
  OS_INSTALLER="${SET_ENVIRONMENT_SCRIPT_DIRECTORY}/src/architecture/${OS}/continue_install.sh"
  log "🟧 OS-specific installer script: ${OS_INSTALLER}"
  export OS_INSTALLER

  if [[ ! -f "${OS_INSTALLER}" ]]; then
    state_set "${FUNCNAME[0]}" "terminal_error_missing_os_installer"
    abort "Missing OS-specific installer script: ${OS_INSTALLER} (OS: ${OS})"
  fi

  # shellcheck disable=SC1090
  source "${OS_INSTALLER}" "${@}"

  local SOURCE_EXIT_CODE
  SOURCE_EXIT_CODE=$?

  if [[ $SOURCE_EXIT_CODE -eq 0 ]]; then
    state_set "${FUNCNAME[0]}" "sourced_os_installer_success"
    log "✅ OS-specific installer success"
  elif [[ $SOURCE_EXIT_CODE -eq 2 ]]; then
    state_set "${FUNCNAME[0]}" "terminal_error_syntax_in_installer"
    abort "❌ Syntax error or invalid command inside: ${OS_INSTALLER}"
  else
    state_set "${FUNCNAME[0]}" "terminal_error_runtime_in_installer_exit_${SOURCE_EXIT_CODE}"
    abort "❌ Installer script exited with non-zero status: ${SOURCE_EXIT_CODE}"
  fi

  # Last step: run a selfcheck
  command_run_as_user "${FF_AGENT_USERNAME}" set_environment_is_working || {
    state_set "${FUNCNAME[0]}" "terminal_error_selfcheck_failed";
    log "Debug state is:"
    grep . "${FF_AGENT_HOME}/state/*."
    abort '❌ The install_set_environment final check of set_environment_is_working failed.';
  }

  log "✅ Set environment is installed and working!"

  state_set "${FUNCNAME[0]}" 'success'
}

install_set_environment

# Turn off tracing
set +x
